#指定构建环境是Node.js，当前版本是稳定版
language: node_js
node_js:
  - 12.1 

# 设置钩子只检测blog-source分支的push变动
branches:
  only:
    - source

# 设置缓存文件
cache:
  directories:
    - node_modules

#在构建之前安装hexo环境
before_install:
  - npm install -g hexo-cli
  - npm install hexo-generator-archive --save

#安装git插件和搜索功能插件
install:
  - npm install
  
#设置git提交名，邮箱；替换真实token到_config.yml文件
before_script:
  - git config --global user.name "maoziya"
  - git config --global user.email "2361725307@qq.com"
  - sed -i "s/gh_token/${mjl_token}/g" ./_config.yml

# 执行清缓存，生成网页操作
script:
  - hexo clean
  - hexo generate
  - hexo deploy
  
  